// <auto-generated />
using System;
using FireAlarmApplication.Web.Modules.AlertSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FireAlarmApplication.Web.UserManagement
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20250922192316_update_202509222221")]
    partial class update202509222221
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user_management")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApnsToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EnableEmailNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnablePushNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableSmsNotification")
                        .HasColumnType("boolean");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("HomeLocation")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocationTrackingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("LocationAccuracy")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("LocationUpdateFrequencyMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocation")
                        .HasDatabaseName("ix_users_current_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CurrentLocation"), "GIST");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("HomeLocation")
                        .HasDatabaseName("ix_users_home_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeLocation"), "GIST");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_active");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_users_phone");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", "user_management");
                });
#pragma warning restore 612, 618
        }
    }
}
