// <auto-generated />
using System;
using FireAlarmApplication.Web.Modules.FireDetection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FireAlarmApplication.Web.Migrations
{
    [DbContext(typeof(FireDetectionDbContext))]
    partial class FireDetectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FireAlarmApplication.Web.Modules.FireDetection.Models.FireDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("Brightness")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FireRadiativePower")
                        .HasPrecision(10, 3)
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasComment("Geographic location using WGS84 coordinate system");

                    b.Property<double>("RiskScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Satellite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_fire_detections_detected_at");

                    b.HasIndex("RiskScore")
                        .HasDatabaseName("ix_fire_detections_risk_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fire_detections_status");

                    b.HasIndex("Status", "DetectedAt")
                        .HasDatabaseName("ix_fire_detections_status_detected_at");

                    b.ToTable("fire_detections", "fire_detection");
                });
#pragma warning restore 612, 618
        }
    }
}
