// <auto-generated />
using System;
using FireAlarmApplication.Web.Modules.AlertSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FireAlarmApplication.Web.Modules.AlertSystem.Migrations
{
    [DbContext(typeof(AlertSystemDbContext))]
    partial class AlertSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alert_system")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.AlertFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("ConfidenceImpact")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("DistanceToFireKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("FireAlertId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("ReliabilityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("UserLatitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("UserLongitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FireAlertId")
                        .HasDatabaseName("ix_alert_feedbacks_fire_alert_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_alert_feedbacks_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_alert_feedbacks_user_id");

                    b.HasIndex("FireAlertId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_alert_feedbacks_alert_user");

                    b.ToTable("alert_feedbacks", "alert_system");
                });

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowFeedback")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double>("MaxDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("MinConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TargetUserRole")
                        .HasColumnType("integer");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_alert_rules_active");

                    b.HasIndex("TargetUserRole")
                        .HasDatabaseName("ix_alert_rules_user_role");

                    b.HasIndex("TargetUserRole", "IsActive")
                        .HasDatabaseName("ix_alert_rules_role_active");

                    b.ToTable("alert_rules", "alert_system");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowFeedback = true,
                            CreatedAt = new DateTime(2025, 9, 7, 20, 44, 18, 438, DateTimeKind.Utc).AddTicks(7520),
                            Description = "Vatandaşlar için yakın yangın uyarıları",
                            IsActive = true,
                            MaxDistanceKm = 15.0,
                            MessageTemplate = "{Distance}km uzağınızda yangın tespit edildi. Güvenirlik: %{Confidence}. Dikkatli olun.",
                            MinConfidence = 50.0,
                            Name = "Vatandaş - Yakın Mesafe",
                            TargetUserRole = 0,
                            TitleTemplate = "DİKKAT: Yangın Tespiti - {Location}"
                        },
                        new
                        {
                            Id = 2,
                            AllowFeedback = false,
                            CreatedAt = new DateTime(2025, 9, 7, 20, 44, 18, 438, DateTimeKind.Utc).AddTicks(7525),
                            Description = "Orman görevlileri için tüm şüpheli tespitler",
                            IsActive = true,
                            MaxDistanceKm = 50.0,
                            MessageTemplate = "{Distance}km mesafede şüpheli yangın tespiti. Güvenirlik: %{Confidence}. Kontrol edilmesi gerekiyor.",
                            MinConfidence = 30.0,
                            Name = "Orman Görevlisi - Geniş Alan",
                            TargetUserRole = 1,
                            TitleTemplate = "Şüpheli Yangın Tespiti - {Location}"
                        },
                        new
                        {
                            Id = 3,
                            AllowFeedback = false,
                            CreatedAt = new DateTime(2025, 9, 7, 20, 44, 18, 438, DateTimeKind.Utc).AddTicks(7527),
                            Description = "İtfaiye için yüksek güvenirlikli yangınlar",
                            IsActive = true,
                            MaxDistanceKm = 100.0,
                            MessageTemplate = "{Distance}km mesafede yangın tespit edildi. Güvenirlik: %{Confidence}. Acil müdahale gerekli.",
                            MinConfidence = 60.0,
                            Name = "İtfaiye - Acil Müdahale",
                            TargetUserRole = 2,
                            TitleTemplate = "ACİL: Yangın Müdahale - {Location}"
                        });
                });

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.FireAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("CenterLatitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLongitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FireDetectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastFeedbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("MaxRadiusKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NegativeFeedbackCount")
                        .HasColumnType("integer");

                    b.Property<double>("OriginalConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("PositiveFeedbackCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FireDetectionId")
                        .HasDatabaseName("ix_fire_alerts_fire_detection_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fire_alerts_status");

                    b.HasIndex("CenterLatitude", "CenterLongitude")
                        .HasDatabaseName("ix_fire_alerts_location");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_fire_alerts_status_expires");

                    b.ToTable("fire_alerts", "alert_system");
                });

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.UserAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AlertMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("CanProvideFeedBack")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceToFireKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("FireAlertId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("UserLatitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("UserLongitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("double precision");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FireAlertId")
                        .HasDatabaseName("ix_user_alerts_fire_alert_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_alerts_user_id");

                    b.HasIndex("IsDelivered", "CreatedAt")
                        .HasDatabaseName("ix_user_alerts_delivery_status");

                    b.HasIndex("UserId", "FireAlertId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_alerts_user_fire");

                    b.ToTable("user_alerts", "alert_system");
                });

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.AlertFeedback", b =>
                {
                    b.HasOne("FireAlarmApplication.Shared.Contracts.Models.FireAlert", "FireAlert")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FireAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireAlert");
                });

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.UserAlert", b =>
                {
                    b.HasOne("FireAlarmApplication.Shared.Contracts.Models.FireAlert", "FireAlert")
                        .WithMany("UserAlerts")
                        .HasForeignKey("FireAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireAlert");
                });

            modelBuilder.Entity("FireAlarmApplication.Shared.Contracts.Models.FireAlert", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("UserAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
